title: "P&eacute;ter S&oacute;lymos"
description: "Statistical computing meets environmental conservation"

#baseurl:  http://localhost:4000
baseurl: http://peter.solymos.org/web-update

include: [".htaccess"]
exclude: ["README.md","LICENSE.md"]
timezone:    America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
markdown_ext: "markdown,mkdown,mkdn,mkd,md,Rmd"

# Bootswatch theme (cosmo)
theme: flatly
# fancy fonts on/off
fancyfonts: true
# navbar style: inverse, transparent
navbar: transparent

disqus: petersolymos
ads: true

author: '<a href="http://peter.solymos.org">P&eacute;ter S&oacute;lymos</a>'

gems:
  - jekyll-feed
